main2 = {
	"taco":["taco"],
	"burrito":["burrito"],
	"nacho":["nacho"],
	"enchilada":["enchilada"],
	"tortilla":["tortilla"],
	"double double" : ["bun", "burger"],
	"burger":["burger", "bun"],
	"3 by 3":["3 by 3", "burger", "bun"],
	"10 by 10":["10 by 10", "burger", "bun"],
	"5 by 5":["5 by 5", "burger", "bun"],
	"4 by 4":["4 by 4", "burger", "bun"],
	"100 by 100":["100 by 100","burger", "bun"],
	"500 by 500":["500 by 500", "burger", "bun"],
	"50 by 50":["50 by 50", "burger", "bun"],
	"guacamole":["guacamole","condiments"],
	"chips" : ["chips","snack"],
	"fish" : ["fish", "seafood", "white meat"],
	"taquito" : ["taco"],
	"shake" : ["shake","cold", "beverage"],
	"coffee":["coffee", "beverage"],
	"beer" : ["beer", "alcohol", "beverage"],
	"lemonade" : ["lemonade", "cold", "beverage"],
	"dr pepper" : ["dr pepper","cold", "beverage"],
	"coke" : ["coke","cold", "beverage"],
	"seven up" : ["seven up", "cold" ,"beverage"],
	"salad":["salad"],
	"oatmeal":["oat"],
	"wrap":["wrap"],
	"muffin":["muffin"],
	"croissant":["croissant", "bread"],
	"poutine":["poutine","fries", "snack"],
	"hotcake":["pancake"],
	"pancake":["pancake"],
	"pie":["pie"],
	"sandwich":["sandwich", "bread"],
	"bagel":["bagel", "bread"],
	"fries":["fries", "snack"],
	"flurry":["flurry","dessert"],
	"milk":["milk", "dairy", "beverage"],
	"nugget":["nugget","snack"],
	"bites":["snack"],
	"latte" : ["latte","beverage"],
	"yogurt" : ["yogurt","dairy"],
	"smoothie" : ["smoothie","beverage"],
	"bbq":["barbecue"],
	"ranch" : ["ranch","condiments"],
	"buffalo ranch":["buffalo ranch","condiments"],
	"chocolate" : ["chocolate"],
	"candies":["candies", "snack"],
	"fruit" : ["fruit"],
	"juice":["juice","beverage"],
	"orange" : ["orange","fruit"],
	"strawberry" : ["strawberry","berry","fruit",],
	"banana" : ["banana","fruit"],
	"steak" : ["steak"],
	"chicken" : ["chicken", "poultry", "white meat"],
	"meat" : ["meat"],
	"beef" : ["beef", "red meat"],
	"asada" : ["asada","beef", "red meat"],
	"sausage" : ["sausage"],
	"bacon" : ["bacon", "red meat"],
	"wings" : ["wings", "poultry", "white meat"],
	"buttermilk crispy chicken" : ["chicken","poultry" ,"white meat"],
	"blt" : ["blt", "bacon", "red meat", "lettuce", "tomato"],
	"minute maid" : ["minute maid","beverage"],
	"apple" : ["apple","fruit"],
	"espresso" : ["espresso","coffee", "beverage"],
	"apple dippers":["apple dippers","fruit", "condiments"],
	"mustard sauce" : ["mustard sauce", "condiments"],
	"cbo" : ["cbo","bacon", "cheese", "red meat", "dairy"],
	"sprite" : ["sprite","cold" ,"beverage"],
	"iced tea" : ["iced tea","cold", "beverage"],
	"cookie" : ["cookie", "snack"],
	"mcgriddle" : ["mcgriddle","sandwich","bread"],
	"ice cream" : ["ice cream", "dessert"],
	"fudge" : ["fudge","dessert"],
	"sundae" : ["sundae","dessert"],
	"hot chocolate" : ["hot chocolate", "beverage"],
	"hash brown" : ["hashbrown", "potato" ,"snack"],
	"parfait" : ["parfait","dessert"],
	"iced coffee" : ["iced coffee","coffee","cold", "beverage"],
	"snack" : ["snack"],
	"bread" : ["bread"],
	"turkey" : ["turkey", "poultry","white meat"],
	"turkey ruben" : ["ruben", "turkey", "poultry", "white meat"],
	"caprese" : ["caprese","salad"],
	"parm" : ["parmesan","cheese", "dairy"],
	"parmesan" : ["parmesan","cheese", "dairy"],
	"mozzarella" : ["mozzarella", "cheese", "dairy"],
	"crab" : ["crab", "seafood", "white meat"],
	"surf" : ["seafood", "white meat"],
	"turf" : ["red meat"],
	"muffuletta" : ["muffuletta","bread"],
	"baguette" : ["baguette","bread"],
	"peanut butter" : ["peanut butter"],
	"cordon bleu" : ["cordon bleu", "meat"],
	"reuben" : ["reuben", "red meat"],
	"tuna" : ["tuna","fish", "seafood", "white meat"],
	"pesto" : ["pesto"],
	"kids" : ["kids"],
	"pork" : ["pork", "red meat"],
	"monte cristo" : ["monte cristo", "ham", "red meat"],
	"pepperoni" : ["pepperoni", "red meat"],
	"salami" : ["salami","red meat"],
	"brownie" : ["brownie","dessert"],
	"breakfast" : ["breakfast"],
	"spinach" : ["spinach", "greens", "vegetable"],
	"lettuce" : ["lettuce","greens", "vegetable"],
	"slaw" : ["salad"],
	"hummus" : ["hummus", "condiments"],
	"green" : ["greens"],
	"croutons" : ["croutons", "bread", "snack"],
	"omelet" : ["omelette","egg", "poultry"] , "omelette" : ["omelette","egg", "poultry"],
	"soup" : ["soup"],
	"baked" : ["baked"],
	"fried" : ["fried"],
	"roast" : ["roast"],
	"cheesecake" : ["cheesecake","dessert"],
	"rice" : ["rice"],
	"rotisserie" : ["rotisserie"],
	"teriyaki" : ["teriyaki"],
	"marinara" : ["marinara","condiments"],
	"boneless" : ["boneless"],
	"wheat" : ["wheat"],
	"pizza" : ["pizza"],
	 "flatizza" : ["pizza"],
	"noodle" : ["noodle"],
	"chili" : ["chili"],
	"broccoli" : ["broccoli", "greens", "vegetable"],
	"salsa" : ["salsa","condiments"],
	"fajita" : ["fajita"],
	"carnitas" : ["carnitas", "red meat"],
	"brabacoa" : ["brabacoa", "meat"],
	"sugar free" : ["sugar free"],
	"gluten free" : ["gluten free"],
	"caffe" : ["beverage"],
	"brie" : ["brie", "cheese", "dairy"],
	"stew" : ["stew"],
	"seafood" : ["seafood", "white meat"],
	"honey" : ["honey"],
	"raisin" : ["raisin"],
	"grain" : ["grain"],
	"bran" : ["bran","grain"],
	"chorizo" : ["chorizo","sausage", "pork", "red meat"],
	"gumbo" : ["gumbo","stew"],
	"watermelon" : ["watermelon", "fruit"],
	"breadstick" : ["breadstick","bread", "snack"],
	"vegetable" : ["vegetable"],
	"veggie" : ["vegetable"],
	"olive" : ["olive"],
	"blueberry" : ["blueberry","berry", "fruit"],
	"kale" : ["kale", "vegetable"],
	"barley" : ["barley","grain"],
	"scone" : ["scone", "cake", "snack"],
	"curried" : ["curry"],
	"curry" : ["curry"],
	"lentil" : ["lentil"],
	"leek" : ["leek", "vegetable"],
	"potato" : ["potato","vegetable"],
	"tomato" : ["tomato", "vegetable"],
	"onion" : ["onion", "vegetable"],
	"bean" : ["beans"],
	"panini" : ["panini", "bread", "sandwich"],
	"artisan" : ["artisan"],
	"focaccia" : ["focaccia","bread"],
	"salt" : ["salt", "condiments"],
	"sugar" : ["sugar", "condiments"],
	"carrot" : ["carrot", "vegetable"],
	"pumkin" : ["pumkin", "vegetable"],
	"almond" : ["almond", "nut"],
	"peanut" : ["peanut", "nut"],
	"walnut" : ["walnut","nut"],
	"hazelnut" : ["hazelnut", "nut"],
	"cashew" : ["cashew", "nut"],
	"pistachio" : ["pistachio", "nut"],
	"pastry" : ["pastry", "dessert"],
	"soynut" : ["soynut","nut"],
	"bisque" : ["bisque", "soup"],
	"macaroni" : ["macaroni"],
	"pasta": ["pasta"],
	"mango" : ["mango", "fruit"],
	"arugula" : ["arugula"],
	"pina colada" : ["pina colada","cocktail", "alcohol", "beverage"],
	"mushroom" : ["mushroom"],
	"granola" : ["granola","snack"],
	"minestrone" : ["minestrone","soup"],
	"pita" : ["pita","bread"],
	"lahvash" : ["lahvash","bread"],
	"oats" : ["oat"],
	"raspberry" : ["raspberry","berry", "fruit"],
	"strudel":["strudel","pastry"],
	"asiago" : ["asiago","cheese", "dairy"],
	"cappuccino" : ["cappuccino","coffee","beverage"],
	"melon" : ["melon","fruit"],
	"grapes" : ["grapes","fruit"],
	"peach" : ["peach", "fruit"],
	"rocky road" : ["rocky road","dessert"],
	"cream cheese" : ["cream cheese","cheese", "dairy"],
	"shortbread" : ["shortbread","biscuit", "snack"],
	"pretzel" : ["pretzel", "snack"],
	"ciabatta" : ["bread"],
	"alfredo" : ["alfredo","pasta"],
	"cereal" : ["cereal", "breakfast"],
	"fat free" : ["fat free"],
	"iced" : ["cold"],
	"vodka" : ["vodka", "alcohol", "beverage"],
	"fagioli" : ["fagioli", "pasta"],
	"pecan" : ["pecan","nut"],
	"paneer" : ["paneer", "dairy"],
	"fennel" : ["fennel"],
	"chowder" : ["chowder","soup"],
	"kolache" : ["kolache", "pastry"],
	"lobster" : ["lobster", "seafood", "white meat"],
	"muesli" : ["oat", "breakfast"],
	"berry" : ["berry", "fruit"],
	"palmier" : ["palmier","pastry", "dessert"],
	"chai" : ["chai","beverage"],
	"sauce" : ["condiments"],
	"clam" : ["clam", "seafood", "white meat"],
	"croisbun" : ["bread"],
	"macchiato" : ["macchiato","coffee","beverage"],
	"shrimp" : ["shrimp", "seafood", "white meat"],
	"macadamia" : ["nut"],
	"avocado" : ["avocado"],
	"creme de fleur" : ["dessert"],
	"garlic" : ["garlic"],
	"lemon" : ["lemon"],
	"lime" : ["lime"],
	"scallop" : ["scallop", "seafood", "white meat"],
	"tofu" : ["tofu"],
	"wonton" : ["wonton"],
	"miso" : ["miso"],
	"curry" : ["curry"],
	"lo mein" : ["noodle"],
	"cinnamon" : ["cinnamon"],
	"coconut" : ["coconut"],
	"fried rice" : ["fried rice"],
	"edamame" : ["beans", "vegetable"],
	"steamed" : ["steamed"],
	"caramel" : ["caramel"],
	"brown rice" : ["brown rice", "rice"],
	"spring roll" : ["spring roll"],
	"white rice" : ["white rice"],
	"soft taco" : ["soft taco"],
	"sour cream" : ["sour cream", "condiments"],
	"chalupa" : ["chalupa"],
	"crunchwrap" : ["crunchwrap", "wrap"],
	"empanada" : ["pastry", "dessert"],
	 "doritos" : ["nacho"],
	"shorebird" : ["shorebird","poultry","white meat"],
	"baklava" : ["baklava","pastry","dessert"],
	"tzatziki" : ["tzatziki","condiments"],
	 "albacore" : ["fish", "seafood","white meat"],
	"pastrami" : ["pastrami", "meat"],
	"tartar" : ["tartar","condiments"],
	"cream" : ["cream"],
	"roll" : ["wrap"],
	"fruit punch" : ["beverage"],
	"slider" : ["slider"],
	"decaf" : ["decaf"],
	 "aioli" : ["aioli","garlic"],
	"mayonnaise" : ["mayonnaise", "condiments"],
	"grill" : ["grill"],
	"strips" : ["strips"],
	"ketchup" : ["ketchup", "condiments"],
	"dressing" : ["dressing"],
	"jelly" : ["jelly"],
	"icedream" : ["dessert"],
	"waffle" : ["waffle"],
	"poke" : ["fish", "seafood", "white meat", "salad"],
	"sesame" : ["sesame"],
	"kernel" : ["nut"],
	"vinaigrette" : ["dressing"],
	"chz" : ["cheese"],
	"moa kai" : ["moa kai", "burger"],
	"wedge" : ["fries"],
	"diet" : ["diet"],
	"szechuan" : ["szechuan"],
	"vegan" : ["vegan"],
	"pacific soy" : ["soy milk","milk", "beverage"],
	"soy milk" : ["soy milk","milk" ,"beverage"],
	"javiva" : ["javiva","coffee", "beverage"],
	"whipped cream" : ["wipped cream", "condiments"],
	"apricot" : ["apricot", "fruit"],
	"2% \milk" : ["2% \milk","milk", "dairy", "beverage"],
	"whole milk" : ["whole milk", "milk" ,"dairy", "beverage"],
	"non fat milk" : ["non fat milk", "milk","dairy", "beverage"],
	"eggnog" : ["eggnog", "milk", "dairy", "beverage"],
	"canele" : ["pastry"],
	"vanilla" : ["vanilla"],
	"earl grey" : ["earl grey", "tea", "beverage"],
	"white chocolate" : ["white chocolate", "chocolate"],
	"green tea" : ["green tea", "tea", "beverage"],
	"almond milk" : ["almond milk", "milk", "dairy", "beverage"],
	 "canele" : ["canele", "pastry", "dessert"],
	"monkey bread" : ["pastry", "dessert"],
	"bear claw" : ["bearclaw", "pastry", "dessert"],
	"pumkin latte" : ["pumkin latte", "beverage"],
	"dark chocolate" : ["dark chocolate", "chocolate"],
	"macaroon" : ["macaroon", "biscuit", "snack"],
	"kouign amann" : ["pastry", "dessert"],
	"orzo" : ["barley"],
	"cafe au lait" : ["coffee", "beverage"],
	"cherry" : ["cherry", "fruit"],
	"cherry crisp" : ["dessert", "snack"],
	"greek yogurt" : ["greek yogurt", "yogurt", "dairy"],
	"meyer lemon" : ["meyer lemon", "lemon"],
	"caffe con panna" : ["cream", "coffee", "beverage"],
	"creme" : ["cream"],
	"coconut creme" : ["coconut", "cream"],
	"jalapeno" : ["jalapeno"],
	"currant": ["raisin"],
	"danish": ["dessert"],
	"steamer" :["beverage"],
	"curd":["curd", "dairy"],
	"peppermint":["mint"],
	"plum":["plum", "fruit"],
	"financier":["financier", "cake","dessert"],
	"cupcake":["cupcake", "dessert"],
	"black tie":["black tie","cold", "beverage"],
	"chow mein" : ["chow mein", "noodle"],
	"rangoon" : ["wonton"],
	"appetizer" : ["appetizer"],
	"shiitake" : ["shiitake"],
	"sourdough" : ["bread"],
	"prosciuttini" : ["ham", "red meat"],
	"cappacuolo" : ["cappacuolo", "pork", "red meat"],
	"cancro" : ["provolone", "beef", "pepperoni", "red meat"],
	"jersey shores" : ["provolone", "cheese", "ham", "red meat", "cappacuolo"],
	"wheat sub" : ["wheat sub"],
	"balsamic vinaigrette" : ["balsamic vinegar", "dressing"],
	"balsamic vinegar" : ["balsamic vinegar", "dressing"],
	"cherry pepper" : ["pepper"],
	"reduced carb" : ["low carb"],
	"french toast" : ["french toast"],
	"spread" : ["spread"],
	"fish and chips" : ["fish and chips", "fish", "seafood", "white meat", "fries"],
	"half and half" : ["half & half", "milk", "dairy"],
	"syrup" : ["syrup"],
	"oreo" : ["oreo", "cookie"],
	"2 percent" : ["2% \milk", "milk","dairy", "beverage"],
	"bruschetta" : ["bruschetta"],
	"patty" : ["patty"],
	"bun" : ["bun", "bread"],
	"margarine" : ["margarine"],
	"churro" : ["churro"],
	"brunch" : ["brunch"],
	"curly fries" : ["fries"],
	"hella peno" : ["jalapeno", "beef", "red meat"],
	"tater" : [ "tater", "potato", "vegetable"],
	"sun dried tomato" : ["sun dried tomato", "tomato"],
	"portobello" : ["portobello", "mushroom"],
	"sirloin" : ["sirloin", "red meat"],
	"barbecue" : ["barbecue"],
	"cheesy" : ["cheese"],
	"peppercorn" : ["pepper"],
	"soy sauce" : ["condiments"],
	"onion rings" : ["onion rings", "onion"],
	"semolina" : ["semolina"],
	"loaf" : ["bread"],
	"miche" : ["miche", "bread"],
	"nine grain" : ["bread"],
	"muffie" : ["muffie", "cookie"],
	"frontega":["frontega", "sandwich"],
	"rye":["rye", "grain"],
	"demi":["bread"],
	"souffl" : ["souffl","dessert"],
	"cobblestone" : ["bread", "dessert"],
	"souffle" : ["souffle","dessert"],
	"deli" : ["deli"],
	"multigrain" : ["multigrain"],
	"hoagie":["sub"],
	"ginseng":["ginseng"],
	"poppyseed":["poppyseed"],
	"quinoa":["quinoa"],
	"toffee":["toffee"],
	"romaine" : ["romaine", "lettuce", "vegetable"],
	"cheery charger" : ["cold", "beverage"],
	"peenya kowlada" : ["pina colada", "cocktail" ,"alcohol", "beverage"],
	"matcha" : ["matcha", "tea", "beverage"],
	"challah" : ["bread"],
	"mocha" : ["mocha", "coffee", "beverage"],
	"terra stix" : ["snack"],
	"pumpernickel" : ["pumpernickel", "bread"],
	"florentine" : ["greens"],
	"fresca" : ["fresca", "cold", "beverage"],
	"candied" : ["candy"],
	"quesadilla" : ["quesadilla"],
	"unwich" : ["unwich","sandwich", "lettuce"],
	"vito" : ["sub"],
	"smoked" : ["smoked"],
	"alfalfa" : ["greens"],
	"low fat" : ["low fat"],
	"sprout" :["sprout"],
	"frozen" : ["frozen"],
	"organic" : ["organic"],
	"madeline" : ["madeleine", "dessert"],
	"madeleine" : ["madeleine","dessert"],
	 "pastries" : ["pastry"],
	"biscotti" : ["biscotti"],
	"nonfat milk" : ["nonfat milk", "milk", "dairy"],
	"mashed potato" : ["mashed potato"],
	"americano" : ["americano","coffee", "beverage"],
	"gouda" : ["gouda","cheese", "dairy"],
	"bleu cheese" : ["bleu", "cheese", "dairy"],
	"ricotta" : ["ricotta","cheese", "dairy"],
	"angus" : ["angus","beef", "red meat"],
	"formaggi" : ["formaggi", "cheese", "dairy"],
	"cheddar" : ["cheese", "dairy"],
	"falafel" : ["falafel"],
	"halibut" : ["halibut", "fish","seafood","white meat"],
	"sardines" : ["sardines", "fish","seafood","white meat"],
	"anchovie" : ["anchovie", "fish","seafood","white meat"],
	"snapper" : ["snapper", "fish","seafood","white meat"],
	"artichoke": ["artichoke", "vegetable"],
	"arugula": ["arugula", "vegetable"],
	"asparagus": ["asparagus", "vegetable"],
	"aubergine": ["aubergine", "vegetable"],
	"eggplant": ["eggplant", "vegetable"],
	"amaranth": ["amaranth", "vegetable"],
	"legumes": ["legumes", "greens" ,"vegetable"],
	"alfalfa sprouts": ["alfalfa sprouts", "vegetable"],
	"azuki": ["azuki beans", "beans", "vegetable"],
	"bean sprouts": ["bean sprouts", "beans" ,"vegetable"],
	"black beans": ["black beans", "beans","vegetable"],
	"black-eyed peas": ["black-eyed peas","peas", "vegetable"],
	"borlotti bean": ["borlotti bean","beans", "vegetable"],
	"broad beans": ["broad beans", "beans", "vegetable"],
	"chickpeas" : ["chickpeas", "peas", "vegetable"],
	"green beans": ["green beans","beans","vegetable"],
	"kidney beans": ["kidney beans", "beans", "vegetable"],
	"lentils": ["lentils", "greens" ,"vegetable"],
	"lima": ["lima beans","beans","vegetable"],
	"butter bean": ["butter bean","beans","vegetable"],
	"mung beans": ["mung beans", "beans", "vegetable"],
	"navy beans": ["navy beans", "beans", "vegetable"],
	"pinto": ["pinto beans","beans","vegetable"],
	"runner": ["runner beans","beans","vegetable"],
	"split peas": ["split peas","peas", "vegetable"],
	"soy beans": ["soy beans", "beans", "vegetable"],
	"peas": ["peas", "vegetable"],
	"mangetout": ["mangetout", "vegetable"],
	"sanp peas" : ["snap peas", "peas", "vegetable"] ,"beet greens": ["beet greens", "greens" ,"vegetable"],
	"bok choy": ["bok choy", "vegetable"],
	"broccoflower": ["broccoflower", "vegetable"],
	"brussels sprouts": ["brussels sprouts", "vegetable"],
	"cabbage": ["cabbage", "greens" ,"vegetable"],
	"calabrese": ["calabrese", "vegetable"],
	"carrots": ["carrots", "vegetable"],
	"cauliflower": ["cauliflower", "vegetable"],
	"celery": ["celery", "vegetable"],
	"collard greens": ["collard greens","greens" ,"vegetable"],
	"corn salad": ["corn salad", "vegetable"],
	"endive": ["endive", "vegetable"],
	"fiddleheads": ["fiddleheads", "vegetable"],
	"frisee": ["frisee", "vegetable"],
	"fennel": ["fennel", "vegetable"],
	"anise": ["anise", "vegetable"],
	"basil": ["basil", "greens" ,"vegetable"],
	"caraway": ["caraway", "vegetable"],
	"cilantro": ["cilantro", "greens" ,"vegetable"],
	"coriander": ["coriander", "vegetable"],
	"chamomile": ["chamomile", "vegetable"],
	"dill": ["dill", "vegetable"],
	"fennel" :  ["fennel",  "vegetable"],
	"lavender" :  ["lavender",  "vegetable"],
	"lemon grass" :  ["lemon grass","greens" ,  "vegetable"],
	"marjoram" :  ["marjoram",  "vegetable"],
	"oregano" :  ["oregano",  "vegetable"],
	"parsley" :  ["parsley",  "vegetable"],
	"rosemary" :  ["rosemary",  "vegetable"],
	"sage" :  ["sage",  "vegetable"],
	"thyme" :  ["thyme",  "vegetable"],
	"kohlrabi" :  ["kohlrabi",  "vegetable"],
	"maize" :  ["maize",  "vegetable"],
	"corn" :  ["corn",  "vegetable"],
	"sweetcorn" :  ["sweetcorn",  "vegetable"],
	"mushrooms" :  ["mushrooms",  "vegetable"],
	"mustard greens" :  ["mustard greens", "greens" ,"vegetable"],
	"nettles" :  ["nettles",  "vegetable"],
	"spinach" :  ["spinach", "greens" ,"vegetable"],
	"okra" :  ["okra",  "vegetable"],
	"chives" :  ["chives",  "vegetable"],
	"garlic" :  ["garlic",  "vegetable"],
	"leek" :  ["leek",  "vegetable"],
	"shallot" :  ["shallot",  "vegetable"],
	"spring onion" :  ["spring onion",  "vegetable"],
	"green onion" :  ["green onion",  "vegetable"],
	"scallion" :  ["scallion",  "vegetable"],
	"parsley" :  ["parsley",  "vegetable"],
	"peppers" :  ["peppers",  "vegetable"],
	"green pepper red pepper" :  ["green pepper red pepper",  "vegetable"],
	"bell pepper" :  ["bell pepper",  "vegetable"],
	"pimento" :  ["pimento",  "vegetable"],
	"chili pepper" :  ["chili pepper",  "vegetable"],
	"capsicum" :  ["capsicum",  "vegetable"],
	"jalapeno" :  ["jalapeno",  "vegetable"],
	"habanero" :  ["habanero",  "vegetable"],
	"paprika" :  ["paprika",  "vegetable"],
	"tabasco pepper" :  ["tabasco pepper",  "vegetable"],
	"cayenne pepper" :  ["cayenne pepper",  "vegetable"],
	"radicchio" :  ["radicchio",  "vegetable"],
	"rhubarb" :  ["rhubarb",  "vegetable"],
	"root vegetables" :  ["root vegetables",  "vegetable"],
	"beetroot" :  ["beetroot",  "vegetable"],
	"beet" :  ["beet",  "vegetable"],
	"celeriac" :  ["celeriac",  "vegetable"],
	"daikon" :  ["daikon",  "vegetable"],
	"ginger" :  ["ginger",  "vegetable"],
	"parsnip" :  ["parsnip",  "vegetable"],
	"rutabaga" :  ["rutabaga",  "vegetable"],
	"radish" :  ["radish",  "vegetable"],
	"swede" :  ["swede",  "vegetable"],
	"rutabaga" :  ["rutabaga",  "vegetable"],
	"turnip" :  ["turnip", "vegetable"],
	"wasabi" :  ["wasabi", "greens" ,"vegetable"],
	"horseradish" :  ["horseradish",  "vegetable"],
	"white radish" :  ["white radish",  "vegetable"],
	"salsify" :  ["salsify",  "vegetable"],
	"skirret" :  ["skirret",  "vegetable"],
	"topinambur" :  ["topinambur",  "vegetable"],
	"squashes" :  ["squashes",  "vegetable"],
	"acorn squash" :  ["acorn squash",  "vegetable"],
	"butternut squash" :  ["butternut squash",  "vegetable"],
	"banana squash" :  ["banana squash",  "vegetable"],
	"courgette" :  ["courgette",  "vegetable"],
	"zucchini" :  ["zucchini",  "vegetable"],
	"cucumber" :  ["cucumber",  "vegetable"],
	"delicata" :  ["delicata",  "vegetable"],
	"gem squash" :  ["gem squash",  "vegetable"],
	"hubbard squash" :  ["hubbard squash",  "vegetable"],
	"marrow" :  ["marrow",  "vegetable"],
	"squash" :  ["squash",  "vegetable"],
	"cucurbita maxima" :  ["cucurbita maxima",  "vegetable"],
	"patty pans" :  ["patty pans",  "vegetable"],
	"spaghetti squash" :  ["spaghetti squash",  "vegetable"],
	"tat soi" :  ["tat soi",  "vegetable"],
	"tubers" :  ["tubers",  "vegetable"],
	"jicama" :  ["jicama",  "vegetable"],
	"jerusalem artichoke" :  ["jerusalem artichoke",  "vegetable"],
	"sunchokes" :  ["sunchokes",  "vegetable"],
	"sweet potato" :  ["sweet potato",  "vegetable"],
	"taro" :  ["taro",  "vegetable"],
	"yam" :  ["yam",  "vegetable"],
	"turnip greens" :  ["turnip greens",  "vegetable"],
	"water chestnut" :  ["water chestnut",  "vegetable"],
	"watercress" :  ["watercress",  "vegetable"],
	"zucchini" :  ["zucchini",  "vegetable"],
	"spaghettoni" : ["spaghettoni", "pasta"],
	"spaghetti" : ["spaghetti", "pasta"],
	"spaghettini" : ["spaghettini", "pasta"],
	"fedelini" : ["fedelini", "pasta"],
	"vermicelloni" : ["vermicelloni", "pasta"],
	"vermicelli" : ["vermicelli", "pasta"],
	"capellini" : ["capellini", "pasta"],
	"capelli d'angelo" : ["capelli d'angelo", "pasta"],
	"barbina" : ["barbina", "pasta"],
	"bucatini" : ["bucatini", "pasta"],
	"perciatelli" : ["perciatelli", "pasta"],
	"fusilli lunghi" : ["fusilli lunghi", "pasta"],
	"fusilli bucati" : ["fusilli bucati", "pasta"],
	"pici" : ["pici", "pasta"],
	"soba" : ["soba", "pasta"],
	"ziti" : ["ziti", "pasta"],
	"zitoni" : ["zitoni", "pasta"],
	"calamarata" : ["calamarata", "pasta"],
	"calamaretti" : ["calamaretti", "pasta"],
	"cannelloni" : ["cannelloni", "pasta"],
	"cavatappi" : ["cavatappi", "pasta"],
	"cellentani" : ["cellentani", "pasta"],
	"chifferi" : ["chifferi", "pasta"],
	"ditalini" : ["ditalini", "pasta"],
	"fideua" : ["fideua", "pasta"],
	"gomito" : ["gomito", "pasta"],
	"elicoidali" : ["elicoidali", "pasta"],
	"fagioloni" : ["fagioloni", "pasta"],
	"fusilli" : ["fusilli", "pasta"],
	"garganelli" : ["garganelli", "pasta"],
	"gemelli" : ["gemelli", "pasta"],
	"maccheroncelli" : ["maccheroncelli", "pasta"],
	"maltagliati" : ["maltagliati", "pasta"],
	"manicotti" : ["manicotti", "pasta"],
	"marziani" : ["marziani", "pasta"],
	"mezzani pasta" : ["mezzani pasta", "pasta"],
	"mezze penne" : ["mezze penne", "pasta"],
	"mezzi bombardoni" : ["mezzi bombardoni", "pasta"],
	"mostaccioli" : ["mostaccioli", "pasta"],
	"paccheri" : ["paccheri", "pasta"],
	"pasta al ceppo" : ["pasta al ceppo", "pasta"],
	"penne" : ["penne", "pasta"],
	"penne rigate" : ["penne rigate", "pasta"],
	"penne lisce" : ["penne lisce", "pasta"],
	"penne zita" : ["penne zita", "pasta"],
	"pennette" : ["pennette", "pasta"],
	"pennoni" : ["pennoni", "pasta"],
	"rigatoncini" : ["rigatoncini", "pasta"],
	"rigatoni" : ["rigatoni", "pasta"],
	"sagne 'ncannulate" : ["sagne 'ncannulate", "pasta"],
	"spirali" : ["spirali", "pasta"],
	"spiralini" : ["spiralini", "pasta"],
	"trenne" : ["trenne", "pasta"],
	"trennette" : ["trennette", "pasta"],
	"tortiglioni" : ["tortiglioni", "pasta"],
	"tuffoli" : ["tuffoli", "pasta"],
	"spaghetti alla chitarra" : ["spaghetti alla chitarra", "pasta"],
	"ciriole" : ["ciriole", "pasta"],
	"bavette" : ["bavette", "pasta"],
	"bavettine" : ["bavettine", "pasta"],
	"fettuce" : ["fettuce", "pasta"],
	"fettuccine" : ["fettuccine", "pasta"],
	"fettucelle" : ["fettucelle", "pasta"],
	"lagane" : ["lagane", "pasta"],
	"lasagne" : ["lasagne", "pasta"],
	"lasagnette" : ["lasagnette", "pasta"],
	"lasagnotte" : ["lasagnotte", "pasta"],
	"linguettine" : ["linguettine", "pasta"],
	"linguine" : ["linguine", "pasta"],
	"mafalde" : ["mafalde", "pasta"],
	"mafaldine" : ["mafaldine", "pasta"],
	"pappardelle" : ["pappardelle", "pasta"],
	"pillus" : ["pillus", "pasta"],
	"pizzoccheri" : ["pizzoccheri", "pasta"],
	"sagnarelli" : ["sagnarelli", "pasta"],
	"scialatelli or scilatielli" : ["scialatelli or scilatielli", "pasta"],
	"stringozzi" : ["stringozzi", "pasta"],
	"tagliatelle" : ["tagliatelle", "pasta"],
	"taglierini" : ["taglierini", "pasta"],
	"trenette" : ["trenette", "pasta"],
	"tripoline" : ["tripoline", "pasta"],
	"campanelle" : ["campanelle", "pasta"],
	"capunti" : ["capunti", "pasta"],
	"casarecce" : ["casarecce", "pasta"],
	"cavatelli" : ["cavatelli", "pasta"],
	"cencioni" : ["cencioni", "pasta"],
	"conchiglie" : ["conchiglie", "pasta"],
	"conchiglioni" : ["conchiglioni", "pasta"],
	"corzetti" : ["corzetti", "pasta"],
	"creste di galli" : ["creste di galli", "pasta"],
	"croxetti" : ["croxetti", "pasta"],
	"farfalle" : ["farfalle", "pasta"],
	"farfalloni" : ["farfalloni", "pasta"],
	"fiorentine" : ["fiorentine", "pasta"],
	"fiori" : ["fiori", "pasta"],
	"foglie d'ulivo" : ["foglie d'ulivo", "pasta"],
	"gigli" : ["gigli", "pasta"],
	"gramigna" : ["gramigna", "pasta"],
	"lanterne" : ["lanterne", "pasta"],
	"lumache" : ["lumache", "pasta"],
	"lumaconi" : ["lumaconi", "pasta"],
	"maltagliati" : ["maltagliati", "pasta"],
	"mandala" : ["mandala", "pasta"],
	"marille" : ["marille", "pasta"],
	"orecchiette" : ["orecchiette", "pasta"],
	"pipe" : ["pipe", "pasta"],
	"quadrefiore" : ["quadrefiore", "pasta"],
	"radiatori" : ["radiatori", "pasta"],
	"ricciolini" : ["ricciolini", "pasta"],
	"ricciutelle" : ["ricciutelle", "pasta"],
	"rotelle" : ["rotelle", "pasta"],
	"rotini" : ["rotini", "pasta"],
	"strozzapreti" : ["strozzapreti", "pasta"],
	"torchio" : ["torchio", "pasta"],
	"trofie" : ["trofie", "pasta"],
	"acini di pepe" : ["acini di pepe", "pasta"],
	"bead-like pasta" : ["bead-like pasta", "pasta"],
	"alfabeto" : ["alfabeto", "pasta"],
	"anelli" : ["anelli", "pasta"],
	"anellini" : ["anellini", "pasta"],
	"couscous" : ["couscous", "pasta"],
	"conchigliette" : ["conchigliette", "pasta"],
	"corallini" : ["corallini", "pasta"],
	"ditali" : ["ditali", "pasta"],
	"ditalini" : ["ditalini", "pasta"],
	"egg barley" : ["egg barley", "pasta"],
	"farfalline" : ["farfalline", "pasta"],
	"fideos" : ["fideos", "pasta"],
	"filini" : ["filini", "pasta"],
	"fregula" : ["fregula", "pasta"],
	"funghini" : ["funghini", "pasta"],
	"israeli couscous" : ["israeli couscous", "pasta"],
	"occhi di pernice" : ["occhi di pernice", "pasta"],
	"orzo" : ["orzo", "pasta"],
	"pastina" : ["pastina", "pasta"],
	"pearl pasta" : ["pearl pasta", "pasta"],
	"ptitim" : ["ptitim", "pasta"],
	"quadrettini" : ["quadrettini", "pasta"],
	"risi" : ["risi", "pasta"],
	"seme di melone" : ["seme di melone", "pasta"],
	"stelle" : ["stelle", "pasta"],
	"stelline" : ["stelline", "pasta"],
	"stortini" : ["stortini", "pasta"],
	"tarhana" : ["tarhana", "pasta"],
	"agnolotti" : ["agnolotti", "pasta"],
	"cannelloni" : ["cannelloni", "pasta"],
	"casoncelli or casonsei" : ["casoncelli or casonsei", "pasta"],
	"casunziei" : ["casunziei", "pasta"],
	"fagottini" : ["fagottini", "pasta"],
	"maultasche" : ["maultasche", "pasta"],
	"mezzelune" : ["mezzelune", "pasta"],
	"occhi di lupo" : ["occhi di lupo", "pasta"],
	"pelmeni" : ["pelmeni", "pasta"],
	"pierogi" : ["pierogi", "pasta"],
	"ravioli" : ["ravioli", "pasta"],
	"sacchettini" : ["sacchettini", "pasta"],
	"sacchettoni" : ["sacchettoni", "pasta"],
	"tortellini" : ["tortellini", "pasta"],
	"tortelloni" : ["tortellini", "pasta"],
	"chocolate milk" : ["chocolate milk", "milk", "dairy", "beverage"],
	"cheese" : ["cheese", "dairy"],
	"anchovy" : ["anchovy", "fish", "seafood", "white meat"],
	"angelfish" : ["angelfish", "fish", "seafood", "white meat"],
	"angelshark" : ["angelshark", "fish", "seafood", "white meat"],
	"barracuda" : ["barracuda", "fish", "seafood", "white meat"],
	"basking shark" : ["basking shark", "fish", "seafood", "white meat"],
	"blenny" : ["blenny", "fish", "seafood", "white meat"],
	"blowfish" : ["blowfish", "fish", "seafood", "white meat"],
	"bluefin tuna" : ["bluefin tuna", "fish", "seafood", "white meat"],
	"blue shark" : ["blue shark", "fish", "seafood", "white meat"],
	"bonito" : ["bonito", "fish", "seafood", "white meat"],
	"bony fish" : ["bony fish", "fish", "seafood", "white meat"],
	"bull shark" : ["bull shark", "fish", "seafood", "white meat"],
	"catfish" : ["catfish", "fish", "seafood", "white meat"],
	"clownfish" : ["clownfish", "fish", "seafood", "white meat"],
	"cod" : ["cod", "fish", "seafood", "white meat"],
	"coelacanth" : ["coelacanth", "fish", "seafood", "white meat"],
	"cookiecutter shark" : ["cookiecutter shark", "fish", "seafood", "white meat"],
	"crappie" : ["crappie", "fish", "seafood", "white meat"],
	"darter" : ["darter", "fish", "seafood", "white meat"],
	"devil ray" : ["devil ray", "fish", "seafood", "white meat"],
	"dogfish" : ["dogfish", "fish", "seafood", "white meat"],
	"dory" : ["dory", "fish", "seafood", "white meat"],
	"dragonfish" : ["dragonfish", "fish", "seafood", "white meat"],
	"dunkleosteus" : ["dunkleosteus", "fish", "seafood", "white meat"],
	"eel" : ["eel", "fish", "seafood", "white meat"],
	"electric eel" : ["electric eel", "fish", "seafood", "white meat"],
	"elver" : ["elver", "fish", "seafood", "white meat"],
	"emperor angelfish" : ["emperor angelfish", "fish", "seafood", "white meat"],
	"flounder" : ["flounder", "fish", "seafood", "white meat"],
	"glassfish" : ["glassfish", "fish", "seafood", "white meat"],
	"goldfish" : ["goldfish", "fish", "seafood", "white meat"],
	"grayling" : ["grayling", "fish", "seafood", "white meat"],
	"great white shark" : ["great white shark", "fish", "seafood", "white meat"],
	"greenland shark" : ["greenland shark", "fish", "seafood", "white meat"],
	"grouper" : ["grouper", "fish", "seafood", "white meat"],
	"grunion" : ["grunion", "fish", "seafood", "white meat"],
	"gulper eel" : ["gulper eel", "fish", "seafood", "white meat"],
	"guppy" : ["guppy", "fish", "seafood", "white meat"],
	"haddock" : ["haddock", "fish", "seafood", "white meat"],
	"hagfish" : ["hagfish", "fish", "seafood", "white meat"],
	"halibut" : ["halibut", "fish", "seafood", "white meat"],
	"hammerhead shark" : ["hammerhead shark", "fish", "seafood", "white meat"],
	"hatchetfish" : ["hatchetfish", "fish", "seafood", "white meat"],
	"herring" : ["herring", "fish", "seafood", "white meat"],
	"icefish" : ["icefish", "fish", "seafood", "white meat"],
	"jackfish" : ["jackfish", "fish", "seafood", "white meat"],
	"john dory" : ["john dory", "fish", "seafood", "white meat"],
	"koi" : ["koi", "fish", "seafood", "white meat"],
	"lamprey" : ["lamprey", "fish", "seafood", "white meat"],
	"lanternfish" : ["lanternfish", "fish", "seafood", "white meat"],
	"lemon shark" : ["lemon shark", "fish", "seafood", "white meat"],
	"ling cod" : ["ling cod", "fish", "seafood", "white meat"],
	"lungfish" : ["lungfish", "fish", "seafood", "white meat"],
	"mackerel" : ["mackerel", "fish", "seafood", "white meat"],
	"mako shark" : ["mako shark", "fish", "seafood", "white meat"],
	"manta ray" : ["manta ray", "fish", "seafood", "white meat"],
	"marlin" : ["marlin", "fish", "seafood", "white meat"],
	"megalodon" : ["megalodon", "fish", "seafood", "white meat"],
	"megamouth shark" : ["megamouth shark", "fish", "seafood", "white meat"],
	"minnow" : ["minnow", "fish", "seafood", "white meat"],
	"monkfish" : ["monkfish", "fish", "seafood", "white meat"],
	"moray eel" : ["moray eel", "fish", "seafood", "white meat"],
	"mullet" : ["mullet", "fish", "seafood", "white meat"],
	"needlefish" : ["needlefish", "fish", "seafood", "white meat"],
	"nurse shark" : ["nurse shark", "fish", "seafood", "white meat"],
	"oarfish" : ["oarfish", "fish", "seafood", "white meat"],
	"orange roughy" : ["orange roughy", "fish", "seafood", "white meat"],
	"orthacanthu" : ["orthacanthu", "fish", "seafood", "white meat"],
	"paddlefish" : ["paddlefish", "fish", "seafood", "white meat"],
	"parrotfish" : ["parrotfish", "fish", "seafood", "white meat"],
	"pilot fish" : ["pilot fish", "fish", "seafood", "white meat"],
	"piranha" : ["piranha", "fish", "seafood", "white meat"],
	"pollock" : ["pollock", "fish", "seafood", "white meat"],
	"pompano" : ["pompano", "fish", "seafood", "white meat"],
	"porgy" : ["porgy", "fish", "seafood", "white meat"],
	"port jackson shark" : ["port jackson shark", "fish", "seafood", "white meat"],
	"pufferfish" : ["pufferfish", "fish", "seafood", "white meat"],
	"pupfish" : ["pupfish", "fish", "seafood", "white meat"],
	"queen triggerfish" : ["queen triggerfish", "fish", "seafood", "white meat"],
	"quillfish" : ["quillfish", "fish", "seafood", "white meat"],
	"remora" : ["remora", "fish", "seafood", "white meat"],
	"rockfish" : ["rockfish", "fish", "seafood", "white meat"],
	"roughy" : ["roughy", "fish", "seafood", "white meat"],
	"sailfish" : ["sailfish", "fish", "seafood", "white meat"],
	"salmon" : ["salmon", "fish", "seafood", "white meat"],
	"sardine" : ["sardine", "fish", "seafood", "white meat"],
	"sawfish" : ["sawfish", "fish", "seafood", "white meat"],
	"sculpin" : ["sculpin", "fish", "seafood", "white meat"],
	"seabass" : ["seabass", "fish", "seafood", "white meat"],
	"seadragon" : ["seadragon", "fish", "seafood", "white meat"],
	"seahorse" : ["seahorse", "fish", "seafood", "white meat"],
	"shad" : ["shad", "fish", "seafood", "white meat"],
	"shark" : ["shark", "fish", "seafood", "white meat"],
	"skate" : ["skate", "fish", "seafood", "white meat"],
	"smelt" : ["smelt", "fish", "seafood", "white meat"],
	"snapper" : ["snapper", "fish", "seafood", "white meat"],
	"stingray" : ["stingray", "fish", "seafood", "white meat"],
	"sturgeon" : ["sturgeon", "fish", "seafood", "white meat"],
	"sunfish" : ["sunfish", "fish", "seafood", "white meat"],
	"swordfish" : ["swordfish", "fish", "seafood", "white meat"],
	"hree-spine stickleback" : ["hree-spine stickleback", "fish", "seafood", "white meat"],
	"thresher shark" : ["thresher shark", "fish", "seafood", "white meat"],
	"tiger shark" : ["tiger shark", "fish", "seafood", "white meat"],
	"triggerfish" : ["triggerfish", "fish", "seafood", "white meat"],
	"trout" : ["trout", "fish", "seafood", "white meat"],
	"tunny" : ["tunny", "fish", "seafood", "white meat"],
	"turbot" : ["turbot", "fish", "seafood", "white meat"],
	"velvetfish" : ["velvetfish", "fish", "seafood", "white meat"],
	"viperfish" : ["viperfish", "fish", "seafood", "white meat"],
	"walleye" : ["walleye", "fish", "seafood", "white meat"],
	"whale shark" : ["whale shark", "fish", "seafood", "white meat"],
	"whiting" : ["whiting", "fish", "seafood", "white meat"],
	"wrasse" : ["wrasse", "fish", "seafood", "white meat"],
	"yellowjack" : ["yellowjack", "fish", "seafood", "white meat"],
	"yellowtail" : ["yellowtail", "fish", "seafood", "white meat"],
	"zebrafish" : ["zebrafish", "fish", "seafood", "white meat"],
	"bearclaw" : ["bearclaw", "pastry", "dessert"],
	"barbacoa" : ["barbacoa"],
	"mountain dew" : ["mountain dew", "beverage", "cold"],
	"tabouli" : ["tabouli", "salad"],
	"bowlwich" : ["bowlwich"],
	"3g charger boost" : ["juice", "beverage"],
	"tostada" : ["tostada"],
	"pickle": ["pickles"],
	 "spring water 5l": ["pure filtered water", "beverage"],
	"biscuit and gravy": ["biscuit & gravy", "breakfast"],
	"dasani bottled water": ["bottled water", "pure filtered water", "beverage"],
	"crispy square": ["square"],
	"gyro": ["gyro"],
	"hashbrown": ["hashbrown", "potato" ,"snack"],
	"half & half" : ["half & half", "milk", "dairy"],
	"half n half" : ["half & half", "milk", "dairy"],
	"doughnut" : ["doughnut", "dessert"],
	"donut" : ["doughnut", "dessert"],
	"tiki tenders" : ["chicken", "poultry", "white meat"],
	"biscuit": ["biscuits"],
	"6 cold cut combo": ["sandwich", "turkey", "white meat"],
	"mustard": ["mustard", "condiments"],
	"dijon mustard": ["dijon mustard", "mustard", "condiments"],
	"slim john": ["snack bars", "snack"],
	"marshmallow": ["marshmallow"],
	"biscuit": ["biscuits"],
	"oil": ["oil"],
	"vinegar": ["vinegar", "dressing"],
	"protein boost": ["suppliment"],
	"malibu" : ["malibu", "alcohol", "beverage"],
	"cherries": ["cherry", "fruit"],
	"sprinkles topping": ["jimmies"],
	"potsticker" : ["potsticker"],
	"mayonaise" : ["mayonnaise", "condiments"],
	"pico de gallo": ["pico de gallo", "salsa", "condiments"],
	"chick fil a chick n minis": ["chicken", "poultry", "white meat"],
	"red meat" : ["red meat", "meat"],
	"white meat" : ["white meat", "meat"],
	"beverage" : ["beverage"],
	"sweetener" : ["sweetener"],
	"acai primo energy bowl, 16 floz": ["bowl meal"],
	"lasagna" : ["lasagna", "pasta"],
	"hotdog" : ["hot dog", "meat"],
	"hotdog" : ["hotdog", "meat"],
	"dessert" : ["dessert"],
	"blizzard" : ["blizzard", "dessert"],
	"calzone" : ["calzone", "pizza"],
	"tiramisu" : ["tiramisu", "dessert"],
	"bolognese" : ["bolognese"],
	"mahi mahi" : ["mahi mahi", "seafood", "white meat"],
	"corona" : ["corona", "beer", "alcohol", "beverage"],
	"budweiser" : ["budweiser", "beer", "alcohol", "beverage"],
	"heineken" : ["heineken", "beer", "alcohol", "beverage"] ,"tri tip" : ["tri tip", "beef", "red meat"],
	"fish n chips" : ["fish and chips", "fish", "seafood", "white meat", "fries"],
	"ribs" : ["ribs", "meat"],
	"margarita" : ["margarita", "alcohol", "beverage"],
	"merlot" : ["merlot", "wine", "alcohol", "beverage"],
	"chardonnay" : ["chardonnay", "wine", "alcohol", "beverage"],
	"vodka" : ["vodka", "alcohol", "beverage"],
	"pinot noir" : ["pinot noir", "wine", "alcohol", "beverage"],
	"without meat" : ["Meatless"],
	"figs" : ["fig", "fruit"],
	"tomatillo" : ["tomatillo", "vegetable"],
	"guava" : ["guava", "fruit"],
	"kumquat" : ["kumquat", "fruit"],
	"oyster" : ["oyster", "seafood", "white meat"],
	"raspberries" : ["raspberry", "berry", "fruit"],
	"tea" : ["tea", "beverage"],
	"pomegranate" : ["pomegranate", "fruit"],
	"champagne" : ["champagne", "alcohol", "beverage"],
	"hotcake" : ["hotcake", "pancake"],
	"quince" : ["quince", "fruit"],
	"bread" : ["bread"],
	"tamarind" : ["tamarind"],
	"tangelos" : ["tangelo", "fruit"],
	"malt" : ["malt", "grain"] , "hot dog" : ["hot dog", "meat"],
	"mt dew" : ["mountain dew", "cold", "beverage"],
	"pia colada" : ["pina colada", "cocktail", "alcohol", "beverage"],
	"sofritas" : ["sofritas"],
	"gravy" : ["gravy"],
	"trail bar" : ["trail bar", "bar"],
	"horchata" : ["horchata", "beverage"],
	"hot cake" : ["pancake"],
	"eclair" : ["eclair", "pastry", "dessert"],
	"pickle" : ["pickle"],
	"butternut" : ["butternut", "fruit"],
	"gumball" : ["gumball"],
	"freezee" : ["freezee", "cold", "beverage"],
	"pollo" : ["chicken", "poultry" ,"white meat"],
	"caesar" : ["salad"],
	"sea urchin" : ["sea urchin", "seafood"],
	"jager bomb" : ["jager bomb", "alcohol", "beverage"],
	"guacomole" : ["guacamole", "condiments"],
	"entree" : ["entree"],
	"squagel" : ["bagel", "bread"],
	"cobette" : ["corn", "vegetable"],
	"mokalita" : ["hot chocolate", "beverage"],
	"wahoo" : ["wahoo", "fish", "seafood", "white meat"],
	"bruchetta" : ["bruschetta"],
	"ribeye" : ["ribeye", "beef", "red meat"],
	"cracker" : ["cracker", "biscuit"],
	"vegetarian" : ["vegetarian"],
	"prawn" : ["prawn", "seafood", "white meat"],
	"lavash" : ["lahvash", "bread"],
	"martini" : ["martini", "alcohol", "beverage"],
	"antipasto" : ["antipasti", "italian"],
	"antipasti" :["antipasti", "italian"],
	"thousand island" : ["dressing", "condiments"],
	"extravaganzza" : ["pizza"],
	"cabernets" : ["red wine", "alcohol", "beverage"],
	"scrambler" : ["scramble", "egg"],
	"chi chi" : ["cocktail", "alcohol", "beverage"],
	"skillet" : ["skillet"],
	"rugelach" : ["pastry", "dessert"],
	"drink" : ["juice"],
	"dippers" : ["condiments"],
	"duck" : ["duck"],
	"burgundy wine" : ["red wine", "alcohol", "beverage"],
	"barbeque" : ["barbecue"],
	"santa fe" : ["santa fe"] ,'gallo of sonoma pinot noir': ['pinot noir', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'cabernet sauvignon  caymus vineyards napa': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'pb and c': ['peanut butter', 'nut butters', 'spread'],
	'cabernet sauvignon  provenance vineyards rutherford': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'cabernet sauvignon  sterling vintners collection california': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'sutter home chardonnay': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'pinot noir  argyle williamette valley': ['pinot noir', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chardonnay  hess select california': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'shiraz  greg norman shiraz australia': ['shiraz wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chianti  da vinci tus cany': ['chianti', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'twix candy': ['candy'],
	'riunite lambrusco': ['lambrusco', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'cabernet sauvignon  j lohr seven oaks paso robles': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'margaritas  ultimate margarita': ['margarita', 'premixed alcoholic beverage'],
	'Hot Dog': ['frank', 'main course', 'menu item type'],
	'Whipped Topping': ['whipped topping', 'dessert topper', 'topping'],
	'heath candy bar': ['candy bar'],
	'merlot  arancio sicily': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chianti classico  nozzole tus cany': ['chianti', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'merlots  blackstone california': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'beringer white zinfandel': ['white zin', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'white wines of interest  smoking loon viognier california': ['white wine', 'wine', 'alcoholic drink', 'beverage'],
	'merlot  ecco domani delle venezie': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'white wines of interest  st supery sauvignon blanc napa valley': ['sauvingnon blanc', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'fiji natural artesian water': ['pure filtered water', 'beverage'],
	'Snickers Candy Mix In': ['candy'],
	'cabernet sauvignon  v beaulieu vineyard coastal california': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'penfolds cabernet shiraz': ['shiraz wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chianti classico  aziano ruffino tus cany': ['chianti', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'cavit pinot grigio': ['pinot grigio', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'Buster Bar': ['square'],
	'classics  mai tai': ['mai tai', 'premixed alcoholic beverage'],
	'cabernet sauvignon  beringer knights valley': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'Kit Kat Wafer Bar Candy Mix In': ['square'],
	'chardonnay  sonoma cutrer russian river': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'trinchero cabernet sauvignon': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'pinot noir  wildhorse central coast': ['pinot noir', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'red wines of interest  yellow tail shiraz australia': ['shiraz wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'M & Ms Candy Mix In': ['candy'],
	'cabernet sauvignon  robert mondavi napa': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'merlot  fanciscan napa': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'Nestle Crunch Bar Candy Mix In': ['square'],
	'chardonnay  estancia monterey': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'white wines of interest  ecco domani pinot grigio': ['pinot grigio', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'pinot noir  domaine chandon carneros': ['pinot noir', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chianti classico  aziano tus cany': ['chianti', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'champagne and sparkling wine  dom perignon eperney': ['sparkling wine', 'wine', 'alcoholic drink', 'beverage'],
	'cabernet sauvignon  merryvale starmont napa': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'red wines of interest  davinci chianti classico': ['chianti', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chardonnays  clos du bois north coast': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'bass': ['bass', 'whole fish', 'seafood'],
	'entrees  veal marsala or picatta style': ['veal marsala', 'main course', 'menu item type'],
	'chardonnays  lindemans bin 65 australia': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'blueberries': ['blueberry', 'berry', 'fruit', 'flavor'],
	'medium arctic rush slush': ['slushies', 'frozen dessert', 'dessert', 'menu item type'],
	'snickers candy': ['candy'],
	'martinis  cosmopolitan': ['cosmopolitan', 'cocktail', 'alcoholic drink', 'beverage'],
	'san pellegrino sparkling mineral water': ['seltzer water', 'pure filtered water', 'beverage'],
	'richs whip topping': ['whipped topping', 'dessert topper', 'topping'],
	'white zinfandel  copperidge california': ['white zin', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'main course  veal piccata': ['veal', 'meat', 'animal by-product'],
	'merlots  beringer founders estate': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'pinot noir  cambria santa maria valley': ['pinot noir', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'shiraz  rosemount show reserve australia': ['shiraz wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'shiraz  penfolds koonunga hill south australia': ['shiraz wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'zinfandel  ravenswood vintners blend california': ['zinfandel', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chianti classico  castello di querceto tus cany': ['chianti', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chianti classico  ruffino ducale tus cany': ['chianti', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chardonnays  kendall jackson vintners reserve': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'chianti classico  gabbiano tus cany': ['chianti', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'blackberries': ['blackberry', 'berry', 'fruit', 'flavor'],
	'whoppers candy': ['candy'],
	'red wines of interest  penfolds thomas hyland shiraz australia': ['shiraz wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'Nilla Wafers Other Mix In': ['nilla wafers', 'vanilla wafers', 'waffle cookies', 'cookie', 'dessert', 'menu item type'],
	'martinis  blue wave martini': ['martini', 'alcoholic drink', 'beverage'],
	'million dollar margarita': ['margarita', 'premixed alcoholic beverage'],
	'chianti  frescobaldi castiglioni tus cany': ['chianti', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chardonnays  la crema sonoma coast': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'red wines of interest  la crema sonoma coast pinot noir': ['pinot noir', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'marti mojito': ['mojito', 'premixed alcoholic beverage'],
	'cabernet sauvignon  bv beaulieu vineyard coastal california': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'champagne and sparkling wine  korbel brut california': ['sparkling wine', 'wine', 'alcoholic drink', 'beverage'],
	'margaritas  cuervo gold margarita': ['margarita', 'premixed alcoholic beverage'],
	'm and ms candy': ['candy'],
	'chianti  nipozzano tus cany': ['chianti', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'Relish Dog': ['frank', 'main course', 'menu item type'],
	'chianti  danzante tus cany': ['chianti', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'Gumballs Candy Mix In': ['candy'],
	'merlots  bv century cellars': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'9" Mintastic Chip': ['chips', 'snack'],
	'clos du bois merlot': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'Butterfinger Candy Mix In': ['candy'],
	'evian natural spring water': ['pure filtered water', 'beverage'],
	'martinis  california cosmo': ['martini', 'alcoholic drink', 'beverage'],
	'riesling  dr loosen eroica washington': ['riesling', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'bud light': ['beer', 'alcoholic drink', 'beverage'],
	'ruffino lumina pinot grigio': ['pinot grigio', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'hogue johannisberg riesling': ['riesling', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'sauvignon blanc  kim crawford marlborough': ['sauvingnon blanc', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'Whoppers Candy Mix In': ['candy'],
	'downtown martini': ['martini', 'alcoholic drink', 'beverage'],
	'chardonnay  libaio ruffino tus cany': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'krackel candy bar': ['candy bar'],
	'Twix Candy Mix In': ['candy'],
	'margaritas  midori margarita': ['margarita', 'premixed alcoholic beverage'],
	'classics  ultimate bloody mary': ['bloody mary', 'cocktail', 'alcoholic drink', 'beverage'],
	'kendall jackson merlot': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'cabernet sauvignon  coppola diamond series claret california': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'merlot  canoe ridge vineyard washington': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'white wines of interest  beringer white zinfandel': ['white zin', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'samuel adams boston lager': ['beer', 'alcoholic drink', 'beverage'],
	'Rainbow Sprinkles': ['rainbow jimmies', 'jimmies'],
	'chardonnays  fontana candida pinot grigio': ['pinot grigio', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'chardonnay  la crema sonoma coast': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'merlot  robert mondavi private selection california': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'main course  veal marsala': ['veal marsala', 'main course', 'menu item type'],
	'nilla wafers': ['nilla wafers', 'vanilla wafers', 'waffle cookies', 'cookie', 'dessert', 'menu item type'],
	'chardonnays  schmitt sohne riesling  germany': ['riesling', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'pinot noir  mirassou california': ['pinot noir', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'Country Gravy': ['gravy', 'sauce', 'menu item type'],
	'gummi bears': ['gummy bears', 'gummies', 'candy'],
	'chardonnay  penfolds thomas hyland south australia': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'white wines of interest  nobilo sauvignon blanc marlborough new zealand': ['sauvingnon blanc', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'merlot  clos du bois north coast': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chardonnay  clos du bois north coast': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'champagne and sparkling wine  rotari brut italy': ['sparkling wine', 'wine', 'alcoholic drink', 'beverage'],
	'red wines of interest  ravenswood vintners blend zinfandel': ['zinfandel', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'merlot  blackstone california': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'nestle crunch bar': ['square'],
	'champagne and sparkling wine  veuve clicquot yellow label brut reims': ['sparkling wine', 'wine', 'alcoholic drink', 'beverage'],
	'butterfinger candy': ['candy'],
	'kit kat candy bar': ['kit kat candy bar', 'candy bar'],
	'mineral water': ['pure filtered water', 'beverage'],
	'Gummi Bears Candy Mix In': ['candy'],
	'chardonnays  sterling vineyards napa valley': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'strawberries': ['strawberry', 'berry', 'fruit', 'flavor'],
	'small arctic rush slush': ['slushies', 'frozen dessert', 'dessert', 'menu item type'],
	'ecco domani pinot grigio': ['pinot grigio', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'cabernet sauvignon  stags leap wine cellars artemis napa': ['wine', 'alcoholic drink', 'beverage'],
	'chardonnay  sutter home': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'pinot noir  beringer founders estate': ['pinot noir', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'merlot  kendall jackson': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chardonnay  kendall jackson': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'draft  samuel adams': ['beer', 'alcoholic drink', 'beverage'],
	'bottle  smirnoff ice': ['grey goose vodka', 'distilled beverage', 'alcoholic drink', 'beverage'],
	'merlot  sutter home': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'bottled water': ['bottled water', 'pure filtered water', 'beverage'],
	'merlot  columbia crest two vines': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'merlot  copperidge': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'merlot  clos du bois': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'14 rack of ribs': ['ribs', 'meat', 'animal by-product'],
	'cabernet sauvignon  chateau st jean': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'cabernet sauvignon  rodney strong': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'cabernet sauvignon  beaulieu vineyard coastal': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'pinot grigio  ecco domani': ['pinot grigio', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'merlot  robert mondavi winery': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chardonnay  clos du bois': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'cabernet sauvignon  robert mondavi winery': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chardonnay  copperidge': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'shiraz  black opal': ['shiraz wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'chardonnay  sterling': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'midori': ['midori', 'liqueur', 'alcoholic drink', 'beverage'],
	'margaritas': ['margarita', 'premixed alcoholic beverage'],
	'signature prime rib': ['prime rib roast', 'beef', 'red meat', 'meat', 'animal by-product'],
	'white zinfandel  beringer': ['white zin', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'cabernet sauvignon  fetzer valley oaks': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'draft  guinness stout': ['guinness stout', 'stout', 'beer', 'alcoholic drink', 'beverage'],
	'samuel adams light': ['beer', 'alcoholic drink', 'beverage'],
	'cabernet sauvignon': ['cabernet sauvingnon', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'Skinny Lunch, without meat': ['lunch', 'main course', 'menu item type'],
	'persimmon': ['persimmon', 'fruit', 'flavor'],
	'pyramid hefeweizen': ['wheat beer', 'beer', 'alcoholic drink', 'beverage'],
	'figs': ['figs', 'fruit', 'flavor'],
	'tomatillo': ['tomatillos', 'vegetable'],
	'guava': ['guavas', 'tropical fruit', 'fruit', 'flavor'],
	'kumquat': ['kumquat', 'citrus fruit', 'fruit', 'flavor'],
	'oyster crackers': ['oyster crackers', 'cracker'],
	'homemade white sangria': ['sangria', 'alcoholic drink', 'beverage'],
	'conundrum white blend': ['white wine', 'wine', 'alcoholic drink', 'beverage'],
	'raspberries': ['raspberry', 'berry', 'fruit', 'flavor'],
	'Beignets': ['beignets', 'pastries', 'baked goods', 'menu item type'],
	'black and herb teas': ['herb tea', 'tea', 'hot beverage', 'beverage'],
	'wine all table types': ['wine', 'alcoholic drink', 'beverage'],
	'pomegranate': ['pomegranate', 'superfood'],
	'toast whitefrench': ['sliced bread', 'bread', 'baked goods', 'menu item type'],
	'evian or san pellegrino water': ['pure filtered water', 'beverage'],
	'kid pb and j': ['peanut butter', 'nut butters', 'spread'],
	'champagne and sparkling wine': ['sparkling wine', 'wine', 'alcoholic drink', 'beverage'],
	'Rubys Hot Cakes, without sides': ['hotcake', 'pancake'],
	'merlot': ['merlot', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'bridgeview blue moon': ['beer', 'alcoholic drink', 'beverage'],
	'rosemount shiraz': ['shiraz wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'newcastle brown ale': ['ale', 'beer', 'alcoholic drink', 'beverage'],
	'tamarind': ['raw tamarind'],
	'copperidge white zinfandel': ['white zin', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'sole': ['sole', 'whole fish', 'seafood'],
	'homemade sangria': ['sangria', 'alcoholic drink', 'beverage'],
	'tangelo': ['tangelos', 'citrus fruit', 'fruit', 'flavor'],
	'quince': ['quinces', 'fruit', 'flavor'],
	'prickly pear': ['cactus pear', 'fruit', 'flavor'],
	'Skinny Eggs': ['eggs'],
	'Garden Scramble, without toast': ['scrambler', 'breakfast meal'],
	'Eggs Benedict': ['eggs benedict', 'breakfast meal'],
	'chardonnay': ['chardonnay', 'dry white wine', 'white wine', 'wine', 'alcoholic drink', 'beverage'],
	'malt powder': ['malt', 'grain'],
	'tangerine': ['tangerine', 'citrus fruit', 'fruit', 'flavor'],
	'bridgeview blue moon riesling': ['beer', 'alcoholic drink', 'beverage'],
	'papaya': ['papaya', 'tropical fruit', 'fruit', 'flavor'],
	'pear': ['pear', 'fruit', 'flavor'],
	'filet mignon usda choice': ['filet mignon', 'beef', 'red meat', 'meat', 'animal by-product'],
	'whipped butter scoop': ['light butter', 'butter', 'cooking fat'],
	'samual adams lager': ['lager', 'beer', 'alcoholic drink', 'beverage'],
	'nectarine': ['nectarine', 'citrus fruit', 'fruit', 'flavor'],
	'mai tai': ['mai tai', 'premixed alcoholic beverage'],
	'loquat': ['loquats', 'fruit', 'flavor'],
	'ecco domani chianti': ['chianti', 'dry red wine', 'red wine', 'wine', 'alcoholic drink', 'beverage'],
	'sierra nevada pale ale': ['pale ale', 'ale', 'beer', 'alcoholic drink', 'beverage'],
	'pumpkin': ['pumpkin', 'squash', 'vegetable'],
	'boysenberries': ['boysenberry', 'berry', 'fruit', 'flavor'],
	'cranberries whole': ['cranberries', 'berry', 'fruit', 'flavor'],
	'Malt Powder, regular': ['malt', 'grain'],
	'cantaloupe': ['cantaloupes', 'melon', 'fruit', 'flavor'],
	'pigs in a blanket': ['pigs in a blanket', 'fingerfood', 'starter'],
	'Jumbo Hot Dog, without sides': ['frank', 'main course', 'menu item type'],
	'plantain': ['plantain', 'fruit', 'flavor'],
	'ruby hot cakes': ['hotcake', 'pancake'],
	'lychee': ['lychee', 'tropical fruit', 'fruit', 'flavor'],
	 'calamari': ['fried calamari', 'starter'],
	'gummy bears': ['gummy bears', 'gummies', 'candy'],
	'grape': ['grape', 'fruit', 'flavor'],
	'mussels': ['mussels', 'shellfish', 'whole fish', 'seafood'],
	 'fritter': ['fritter', 'side dish'],
	'red bull': ['energy supplement drink', 'beverage'],
	'tapioca': ['tapioca'],
	 'sherbet': ['sherbet'],
	'snickers': ['snickers chocolate bar', 'chocolate bar', 'candy bar'],
	'dipping': ['dip', 'starter'],
	'crepes': ['crepes'],
	 'smores': ["s'mores", 'dessert', 'menu item type'],
	'sushi': ['sushi rolls', 'main course', 'menu item type']
}
main3 = {
	"tea" : ["tea", "beverage"],
	"cola" : ["coke","cold","beverage"],
	"cake":["cake","dessert"],
	"dip" : ["dip","condiments"],
	"egg" : ["egg", "poultry"],
	"sub" : ["sub", "bread"],
	"cheese" : ["cheese", "dairy"],
	"oat" : ["oat"],
	"nut" : ["nut"],
	 "mayo" : ["mayonnaise", "condiments"],
	"wave " : ["beverage"],
	"sixteen" : ["beverage"],
	"tom" : ["sandwich"],
	"pepe" : ["pepe", "sandwich"],
	"dry" : ["dry"],
	"ham" : ["ham", "red meat"],
	"beans" : ["beans"],
	"pibb" : ["cold", "beverage"],
	"hula" : ["meatless"],
	"tart" : ["tart"],
	"lean" : ["suppliment"],
	"chard": ["chard", "vegetable"],
	"eggs" : ["egg", "poultry"],
	"pepsi" : ["pepsi", "cold", "beverage"],
	"nuts" : ["nut"],
	"wing" : ["wings", "poultry", "white meat"],
	"bar" : ["bar"],
	"bowl" : ["bowl"],
	"box" : ["box"],
	"soy" : ["soy"],
	"cone" : ["cone"],
	"soda" : ["soda"],
	"mint" : ["mint"],
	"acai" : ["acai"],
	'rib': ['ribs', 'meat', 'animal by-product'],
	'dog': ['frank', 'main course', 'menu item type'],
	'flan': ['creme caramel', 'dessert'],
	'cocoa': ['cocoa powder'],
	'kiwi': ['kiwi', 'tropical fruit', 'fruit', 'flavor'],
	'toast': ['sliced bread', 'bread', 'baked goods', 'menu item type'],
	'm&m': ["m&m's", 'candy coated chocolate pieces', 'chocolate candies'],
	'mnm' : ["m&m's", 'candy coated chocolate pieces', 'chocolate candies'],
	'veal': ['veal', 'meat', 'animal by-product'],
	'dips': ['dip', 'starter'],
	"feta" : ["cheese", "dairy", "milk"]
}

for key in main2.keys():
	print(key)
for key in main3.keys():
	print(key)