'''
Sample inputs:
1. KALE CHIPS
		ingredients: ORGANIC KALE, ORGANIC CASHEWS, ORGANIC YELLOW BELL PEPPER, ORGANIC ONION, ORGANIC CILANTRO, ORGANIC JALAPENO, ORGANIC LIME JUICE, NUTRITIONAL YEAST, SALT
2. SOUTHERN BARBEQUE, BAKED CRUNCHY BLACK BEAN CHIPS
		ingredients: BLACK BEAN POWDER, RICE FLOUR, SUNFLOWER OIL, SEASONING(MALTODEXTRIN, SUGAR, SALT, SPICES, TOMATO POWDER, BROWN SUGAR, ONION POWDER, TORULA YEAST, VINEGAR, MOLASSES, NATURAL FLAVORS(EXTRACTIVE OF PAPRIKA, CITRIC ACID) WITH NOT MORE THAN 2% LESS OF SUNFLOWER OIL AND SILICON DIOXIDE [PROCESSING AID]), SALBA CHIA SEED, SALT
		nutrients: 
'''
print(__doc__)
print(Dish("SOUTHERN BARBEQUE, BAKED CRUNCHY BLACK BEAN CHIPS"), Dish("KALE CHIPS"))
